apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter 
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventrouter 
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventrouter 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventrouter
subjects:
- kind: ServiceAccount
  name: eventrouter
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  namespace: kube-system
  labels:
    app: eventrouter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventrouter
  template:
    metadata:
      labels:
        app: eventrouter
    spec:
      serviceAccount: eventrouter
      containers:
      - name: eventrouter
        image: ghcr.io/kuoss/eventrouter:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/eventrouter
      volumes:
      - name: config-volume
        configMap:
          name: eventrouter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eventrouter
  namespace: kube-system
data:
  config.json: |
    {
      "sink": "stdout"
    }

# {"verb":"ADDED","event":{"metadata":{"name":"eventrouter-7985dc55cd.18588177b5099e70","namespace":"kube-system","uid":"0bf5d110-24b1-4629-9fe6-44cfef428c46","resourceVersion":"8068","creationTimestamp":"2025-08-04T08:00:06Z","managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2025-08-04T08:00:06Z","fieldsType":"FieldsV1","fieldsV1":{"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:reportingComponent":{},"f:source":{"f:component":{}},"f:type":{}}}]},"involvedObject":{"kind":"ReplicaSet","namespace":"kube-system","name":"eventrouter-7985dc55cd","uid":"5b15cdc2-237c-46ad-887a-e71fbb151ac7","apiVersion":"apps/v1","resourceVersion":"8062"},"reason":"SuccessfulDelete","message":"Deleted pod: eventrouter-7985dc55cd-bh5fb","source":{"component":"replicaset-controller"},"firstTimestamp":"2025-08-04T08:00:05Z","lastTimestamp":"2025-08-04T08:00:05Z","count":1,"type":"Normal","eventTime":null,"reportingComponent":"replicaset-controller","reportingInstance":""}}
# {"verb":"ADDED","event":{"metadata":{"name":"eventrouter-7985dc55cd-bh5fb.18588177b52e9a8b","namespace":"kube-system","uid":"004d1a34-9158-449c-9c84-5a3d5818b27c","resourceVersion":"8069","creationTimestamp":"2025-08-04T08:00:06Z","managedFields":[{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2025-08-04T08:00:06Z","fieldsType":"FieldsV1","fieldsV1":{"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:reportingComponent":{},"f:reportingInstance":{},"f:source":{"f:component":{},"f:host":{}},"f:type":{}}}]},"involvedObject":{"kind":"Pod","namespace":"kube-system","name":"eventrouter-7985dc55cd-bh5fb","uid":"19fe3a6a-edb9-4d67-a3c3-fcc598db317d","apiVersion":"v1","resourceVersion":"7961","fieldPath":"spec.containers{logrotate}"},"reason":"Killing","message":"Stopping container logrotate","source":{"component":"kubelet","host":"kind1-control-plane"},"firstTimestamp":"2025-08-04T08:00:06Z","lastTimestamp":"2025-08-04T08:00:06Z","count":1,"type":"Normal","eventTime":null,"reportingComponent":"kubelet","reportingInstance":"kind1-control-plane"}}
